taxi_nyc_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "***"
      port: 1433
      database: "sqldb-taxi-platform"
      schema: "bronze"
      user: "***"
      password: "***"
      encrypt: True
      trust_cert: False
